# Generated by Django 4.1.9 on 2023-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('ntab', models.CharField(max_length=10)),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amcom', models.DecimalField(blank=True, db_column='AMCOM', decimal_places=2, max_digits=10, null=True)),
                ('kassid', models.IntegerField(blank=True, null=True)),
                ('sum_gp', models.DecimalField(blank=True, db_column='SUM_GP', decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iactive', models.SmallIntegerField(blank=True, db_column='IACTIVE', null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=36, null=True)),
                ('fcard', models.IntegerField(blank=True, null=True)),
                ('ncard', models.IntegerField(blank=True, null=True)),
                ('vid', models.IntegerField(blank=True, db_column='Vid', null=True)),
                ('kol', models.IntegerField(blank=True, db_column='Kol', null=True)),
            ],
            options={
                'db_table': 'SALE',
                'managed': False,
            },
        ),
    ]
